name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-debian:
    strategy:
      fail-fast: false
      matrix:
        release: [stable, testing]

    runs-on: ubuntu-latest
    container: debian:${{ matrix.release }}

    steps:
    - name: Install toolchain
      run: |
        apt-get update
        apt-get install -y rustc cargo git
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
